SUPABASE_URL = "https://gxdmupqopfocmmcxxkbv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZG11cHFvcGZvY21tY3h4a2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg2ODc4NDEsImV4cCI6MjEwNDI2Mzg0MX0.BU3Cjtow8zzMQukTxXo4J-ulJW5M3k1pnX3Dd204u1M"
FAST2SMS_API_KEY = "eBGQYanRZNKVCpMSg3KB5kUxY2QhDnOjxesh3Hqr7FOG792XV9wut4TPhQia"

[supabase]
url = "https://gxdmupqopfocmmcxxkbv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZG11cHFvcGZvY21tY3h4a2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg2ODc4NDEsImV4cCI6MjEwNDI2Mzg0MX0.BU3Cjtow8zzMQukTxXo4J-ulJW5M3k1pnX3Dd204u1M"
